### ISSUE TITLE
Saving credentials

### ISSUE THREAD

**Issue by baldurmen** [wger-project/android#4]
Hi!

I'm really not familiar with Android development, but I've seen that WebView API 18 has deprecated a bunch of password saving functions.

Do you think you could use something like  [setHttpAuthUsernamePassword](https://developer.android.com/reference/android/webkit/WebView.html#setHttpAuthUsernamePassword%28java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String%29) to handle credentials? Having to log-in each time is bothering...

**Comment by rolandgeider** [comment]
I am also not very familiar with Android development, that's why the android application is a very very simple webview wrapper around the website and not much else. There are many other places that could benefit from better integration, but at the moment I don't have the time to investigate this.

At least now we have an issue for it :)
